.\" Manpage for poof
.Dd January 5, 2013
.Dt poof 1
.Os Mac OS X
.Sh NAME
.Nm poof
.Nd List or remove Mac OS X packages
.Sh SYNOPSIS
.Nm Ar package-id
.Sh DESCRIPTION
The
.Nm
command line utility lists or removes Mac OS X packages in a low-level manner, by removing files and directories and then forgetting the metadata about the package (the receipt data).
.Sh EXAMPLES
List packages (but skip from Apple):
.Dl "./poof.py | grep -v com.apple.pkg"
Remove package FlashPlayer:
.Dl "sudo ./poof.py com.adobe.pkg.FlashPlayer"
.Sh SEE ALSO
.Xr pkgutil 1
