.\" Manpage for poof
.Dd March 21, 2017
.Dt poof 1
.Os macOS
.Sh NAME
.Nm poof
.Nd List or uninstall/remove OS X packages
.Sh SYNOPSIS
.Nm Ar package-id
.Sh DESCRIPTION
The
.Nm
command line utility list or uninstall/remove macOS packages in a low-level manner,
it first removes all files and directories declared by the package and
then forget the metadata (the receipt data).
.Sh EXAMPLES
List packages (but skip from Apple):
.Dl "./poof.py | grep -v com.apple.pkg"
Remove package FlashPlayer:
.Dl "sudo ./poof.py com.adobe.pkg.FlashPlayer"
.Sh SEE ALSO
.Xr pkgutil 1
